export const GET_SUDOKU_EASY = "GET_SUDOKU_EASY"
export const GET_SUDOKU_MEDIUM = "GET_SUDOKU_MEDIUM"
export const GET_SUDOKU_HARD = "GET_SUDOKU_HARD"
export const GET_SUDOKU_EXPERT = "GET_SUDOKU_EXPERT"